### ISSUE TITLE
Betreff-Feld im Template

### ISSUE THREAD

**Issue by Hard-Virus** [zencartpro/157-template-winchester#1]
Hallo, ich weiß jetzt nicht ob ich einen Fehler gemacht habe, allerdings erhalte ich bei Aktivierung des Templates "Winchester Responsive" und dem Aufrufen der Kontaktseite folgende Fehlermeldung im LogFile:

PHP Warning: Undefined variable $subject in /includes/templates/winchester_responsive/templates/tpl_contact_us_default.php on line 71.
Dürfte vielleicht daran liegen, dass es im Kontaktformular des Standardtemplatges keine Betreffzeile gibt, in "Winchester Responsive" jeodch schon.

LG

**Comment by webchills** [comment]
Das Template ändert einige bestehende Dateien, unter anderem die includes/modules/pages/contact_us/header_php.php. Prüfe ob Du die wirklich geändert hast.

**Comment by Hard-Virus** [comment]
OK, das war es wohl wirklich. Durch das mehrfache Änderung und Herumkopieren dürfte diese dann wohl untergegangen sein. 
Vielen Dank für die Hilfe
